- name: Examine all stat output of /etc/passwd
  hosts: all
  tasks:
  - name: stat /etc/passwd
    stat:
      path: /etc/passwd
    register: results
  - name: Display stat results
    debug:
      var: results.stat.checksum
